#!/bin/bash

psql << EOF
CREATE USER Read_Only_User WITH LOGIN PASSWORD 'SuP3R$tr0ng462Pa55w0rd' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';
GRANT CONNECT ON DATABASE $POSTGRES_DB TO Read_Only_User;
GRANT USAGE ON SCHEMA public TO Read_Only_User;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES  TO Read_Only_User;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON SEQUENCES TO Read_Only_User;
EOF