name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vishakvinod/pgbackrest:v0.0.1
    - name: Publish the Docker image
      run: docker publish vishakvinod/pgbackrest:v0.0.1
